---
sudo: false
dist: trusty
language: node_js
node_js:
  - '10'
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - touch package.json

install:
  - make install
  - make precompile

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

deploy:
  skip_cleanup: true
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: l1Hx/hQg5iQkGnSNbqcWluHpltZiFjSjPNVebVO9E6JS94ftvA+3PSbJu+eOelWK2vh8lE+YT0xfqEz+bGeAh2UHMm8tgGdiP6xHtp4UtKcwJhm7X2cT9yXCqQu/W/hZkr8/Sh06gkuEVYIgz8UvwEhVDu1kGhB7jQ5qBNqPMANPrOCXKefFs03bPzL/qyWDjetIWGayHJwnYeOSCam42PCVG5wYpSiWpsP9Rio+0eN9vtdwMdoLhHsiCEf8uZGUDw1mjt1fYQ3VBk2yNS0DnaFHvp0mINLXYTpotHjGHydx2Ximq/clODgxDftiykMYgFhdS19voYc5tEE6tJfC5AzzBIKrThYW/TOsU1yCWg6bZYj0eTSDS8TILcvInl989otjYrgMhGFf3KDgYxa55iIelh4FSc9AummI8kCpuSm8m8XTeaaRDdtc9QeLeB16+OlySkSl6FG+k332iCpcVJwt4AOkjaYzPIfz7mFJHXIELJzln8uB2as/Crvs0Rx6ryV887j7N3NSWXAv6bk1lJTipjdHQkITV2fzLmtyAoEjQRgLnFO+7xaLJOfK+ILdtmeKjlg0nJCjwg+2hTN1XXj1HxaCobjbHRJAmtaItAaO/AGsq5cZSTQWDmJ5xMaI7XnwpC12//uxSwrY8NJ0eBtFXMUqmTbr8eu0bSpKiXU=
  on:
    tags: true
    node_js: 10
    repo: Dreamscapes/remote-event-emitter
