---
sudo: false
dist: trusty
language: node_js
node_js:
  - '10'
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - touch package.json

install:
  - make install
  - make precompile

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

deploy:
  skip_cleanup: true
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: 3biFAEEgSKRUimASCx9arDYNUeZ0Nipe2TEH5PsV7itnnQ7ZPDJdVPRu8YDoPAGWoNzOTSzFxZJiISEl40smS4kqQRgN0yq8lqpa9B2/OOIGwk5LnvQqTr9zLhLsdNZNzPqttlXtcZOEYSaMkRNMIwXu9tSOPnxUhe+Up32WTN5uFi7an4zVM4NHGnYKMdd6CRRxtZW9Pl2m/u7VkMsmpoAMJeALs5XQifMx3FR+AnbMB/VuhbuIgbQFNpCUAul14bMFsqEbmg1qw1dCopJPqSnvE4uJVETBozMcvBby+SNH3j5A8bRxslQbntY6LKlRv00EWlcBtnE3cF1BxGCVRlCrE/g5f74JLHBUfEbWrEcEeuhtE9gLRYBkeJByVij/W86mPObTPqoiB4+NC0Fe+8DV6uzuDJKQlthl8c3jYWJeUd9CiBKHHoc6gP+jN2eOXSD/Ge1VLw3ihHOGYSzp+vTdGZ2WDDxYCgDHhLiTTUOJKsDSmVUkdCox1lJcETkzFvXN1iU0FbTPmG25I9fMXxegBZCfEPZkfRB+imIoX4GAE9kxhKhZO5VA3RwLyml5gZ9/irMK4W4uX6V38eme5baViHUKjPJkT9nivsODLzU6JCLgTmqSQc8/MV41va+c5cUgPAC68F/dWNIkK2lJ1beXyDI845pZySHYGntCSBQ=
  on:
    tags: true
    node_js: 10
    repo: Dreamscapes/remote-event-emitter
