---
sudo: false
dist: trusty
language: node_js
node_js:
  - '10'
  - '11'

cache:
  directories:
    - node_modules

before_install:
  - touch package.json

install:
  - make install
  - make precompile

script:
  - make lint
  - make test

after_success:
  - make coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls

deploy:
  skip_cleanup: true
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: jouFqxRNiKPBigphD0+/nfwpbrJHprjcNHAdaf+e8Hc5+6WosydlifJ8wZ6G1kiqTkpUQc5yrcxJJN4WooVzVmrRAHrwTkEvyXSBw8aZVpc6f+cFX2GlxxThsUkpYNosnwsQwQGWqen0qknoaLWuris4UUOgQ2xe9E1gLkJY/nkutWL79l32LyW9SdlZJ01+9L85wH7989iK2tx81RtE5I5Qa2GARgvFFtaFWOUaOzsDUl5HniPPMoCgvkrh9B/RsW1255mSD8iEOeM4Rp6bFUreoI+wkQfk8/Kfe1cTezETpOvZdGpn2CBIKvKEH3H3j8iGzmlaikB8ExnMyD667BAwu4eowhzDKPGxfac1z5P8hwbj4IALp8DuEZvvM3EyjZSLtYWK1BZ361s2icLSguG/X2NhpncXY0LEikn3yds08ZMbUZsQlIlMWvTxZkkO3fEu8R6ebt8znFabU3lT1BUdzpVI54SjO1pTvxpX5LTfXDWAi+4Hpq4UjiD4oJhkXF8BkU9BsQPW2IycG6J3exPuiuDtFf28C5NtOFZWcaqGfF1xcP3uQl8BgVz7H9uSDUbnfikPn/mFTqSFqk7PQitC46fEI3T4uGfvs7YXecb8HN0zSNKfVrL312CVZSzKmsLsGDemuyiJDizysTu15/hB1KJLt4l8yCf9K2FlrrE=
  on:
    tags: true
    node_js: 10
    repo: Dreamscapes/remote-event-emitter
